Check dataLoad's targetPath existence by dataload job's log. (#2465)
* Check dataLoad's targetPath existence by dataload job's log.

Signed-off-by: yn <915093340@qq.com>

* delete check dataloadPath logic of dataset controller.

Signed-off-by: yn <915093340@qq.com>

Signed-off-by: yn <915093340@qq.com>

diff --git a/charts/fluid-dataloader/jindofsx/templates/configmap.yaml b/charts/fluid-dataloader/jindofsx/templates/configmap.yaml
--- a/charts/fluid-dataloader/jindofsx/templates/configmap.yaml
+++ b/charts/fluid-dataloader/jindofsx/templates/configmap.yaml
@@ -30,13 +30,23 @@ data:
   dataloader.distributedLoad: |
     #!/usr/bin/env bash
     set -xe
+    
+    function checkPathExistence() {
+        local targetPath=$1
+        local checkPathResult=$(timeout 30s hadoop fs -ls jindo://$targetPath |& tail -3)
+        local strUnexistence="No such file or directory"
+        if [[ $checkPathResult =~ $strUnexistence ]];then
+            echo -e "dataLoad failed because some paths not exist."
+            exit 1
+        fi
+    }
 
     function distributedLoad() {
         local path=$1
         local replica=$2
         local default=$3
         local cmd="jindo fs -load"
-
+        checkPathExistence "$path"
         if [[ $needLoadMetadata == 'true' ]]; then
             echo -e "--- enable metaCache"
             cmd="$cmd -meta"
diff --git a/charts/fluid-dataloader/juicefs/templates/configmap.yaml b/charts/fluid-dataloader/juicefs/templates/configmap.yaml
--- a/charts/fluid-dataloader/juicefs/templates/configmap.yaml
+++ b/charts/fluid-dataloader/juicefs/templates/configmap.yaml
@@ -23,6 +23,14 @@ data:
         podNames=(${podNames//:/ })
 
         ns="$POD_NAMESPACE"
+    
+        checkPathResult=$(/usr/local/bin/kubectl -n $ns exec -it "${podNames[0]}" -- timeout 30s /bin/ls $targetPath |& head -3)
+        strUnexistence="No such file or directory"
+        if [[ $checkPathResult =~ $strUnexistence ]]; then
+            echo -e "dataLoad failed because some paths not exist."
+            exit 1
+        fi
+    
         if [ $EDITION == 'community' ]
         then
         for((i=0;i<${#podNames[@]};i++)) do
