add timeout before parallel workers ready, scale workers to zero when finished.
Signed-off-by: xliuqq <xlzq1992@gmail.com>

diff --git a/charts/fluid-datamigrate/juicefs/templates/configmap.yaml b/charts/fluid-datamigrate/juicefs/templates/configmap.yaml
--- a/charts/fluid-datamigrate/juicefs/templates/configmap.yaml
+++ b/charts/fluid-datamigrate/juicefs/templates/configmap.yaml
@@ -6,34 +6,33 @@ metadata:
     release: {{ .Release.Name }}
     role: datamigrate-job
 data:
+  check_ssh.sh: |
+    #!/bin/bash
+    # usage: check_ssh.sh worker01 work02
+    for host in "$@"; do
+      gotStatus="-1"
+      wantStatus="0"
+      while [ $gotStatus -ne $wantStatus ]
+      do
+        ssh $host ls . > /dev/null 2>&1
+        gotStatus=$?
+        if [ $gotStatus -ne $wantStatus ]; then
+          echo "$(date '+%Y/%m/%d %H:%M:%S') Failed to ssh pod $host, retrying in 1 second..."
+          sleep 1
+        fi
+      done
+      echo "Successfully ssh pod: $host"
+    done
   datamigrate.sh: |
     #!/bin/bash
     set -e
 
-    function check_ssh() {
-      # +e to prevent quit when ssh failed
-      set +e
-      for host in "$@"; do
-        gotStatus="-1"
-        wantStatus="0"
-        while [ $gotStatus -ne $wantStatus ]
-        do
-          ssh $host ls . > /dev/null 2>&1
-          gotStatus=$?
-          if [ $gotStatus -ne $wantStatus ]; then
-            echo "$(date '+%Y/%m/%d %H:%M:%S') Failed to ssh pod $host, retrying in 1 second..."
-            sleep 1
-          fi
-        done
-        echo "Successfully ssh pod: $host"
-      done
-      set -e
-    }
-
     function main() {
       echo "juicefs datamigrate job start..."
+      scripts_dir=$(cd $(dirname $0); pwd)
 
       # handle parallel migrations
+      parallel_options=""
       if [ $PARALLELISM -gt 1 ]
       then
         # format like
@@ -42,25 +41,25 @@ data:
         #Host data-migrate-migrate-workers-1
         #  HostName data-migrate-migrate-workers-1.data-migrate-migrate-svc
         workers=$(grep "Host " /root/.ssh/config  | cut -d " " -f 2)
-        check_ssh ${workers}
+        timeout ${WORKERS_READY_TIMEOUT} ${scripts_dir}/check_ssh.sh ${workers}
 
         workers=$(echo "$workers" | tr '\n' ',')
         workers=${workers%?}
-        echo "distribute data migrate using $workers"
 
-        timeout $TIMEOUT /usr/local/bin/juicefs sync --worker ${workers} --manager-addr ${POD_IP} {{ .Values.datamigrate.migrateFrom }} {{ .Values.datamigrate.migrateTo }} $OPTION
+        parallel_options="--worker ${workers} --manager-addr ${POD_IP}"
+        echo "distribute data migrate using options: $parallel_options"
+      fi
+
+      if [ $EDITION == 'community' ]
+      then
+        timeout $TIMEOUT /usr/local/bin/juicefs sync $parallel_options {{ .Values.datamigrate.migrateFrom }} {{ .Values.datamigrate.migrateTo }} $OPTION
       else
-        if [ $EDITION == 'community' ]
-        then
-          timeout $TIMEOUT /usr/local/bin/juicefs sync {{ .Values.datamigrate.migrateFrom }} {{ .Values.datamigrate.migrateTo }} $OPTION
-        else
-          {{- range $key, $val := .Values.datamigrate.options }}
-          {{- if eq $key "formatCmd" }}
-          {{ $val }}
-          {{- end }}
-          {{- end }}
-          timeout $TIMEOUT /usr/bin/juicefs sync {{ .Values.datamigrate.migrateFrom }} {{ .Values.datamigrate.migrateTo }} $OPTION
-        fi
+        {{- range $key, $val := .Values.datamigrate.options }}
+        {{- if eq $key "formatCmd" }}
+        {{ $val }}
+        {{- end }}
+        {{- end }}
+        timeout $TIMEOUT /usr/bin/juicefs sync $parallel_options {{ .Values.datamigrate.migrateFrom }} {{ .Values.datamigrate.migrateTo }} $OPTION
       fi
       echo "juicefs datamigrate job end."
     }
