Check dataLoad's targetPath existence by dataLoad job's log.
Signed-off-by: yn <915093340@qq.com>

diff --git a/charts/fluid-dataloader/goosefs/templates/configmap.yaml b/charts/fluid-dataloader/goosefs/templates/configmap.yaml
--- a/charts/fluid-dataloader/goosefs/templates/configmap.yaml
+++ b/charts/fluid-dataloader/goosefs/templates/configmap.yaml
@@ -41,10 +41,21 @@ data:
   dataloader.goosefs.distributedLoad: |
     #!/usr/bin/env bash
     set -xe
+    
+    function checkPathExistence() {
+        local path=$1
+        local checkPathResult=$(timeout 30s goosefs fs ls "$path" | tail -1)
+        local strUnexistence="does not exist"
+        if [[ $checkPathResult =~ $strUnexistence ]]; then
+            echo -e "dataLoad failed because some paths not exist."
+            exit 1
+        fi
+    }
 
     function distributedLoad() {
         local path=$1
         local replica=$2
+        checkPathExistence "$path"
         goosefs fs setReplication --max $replica -R $path
         if [[ $needLoadMetadata == 'true' ]]; then
             time goosefs fs distributedLoad -Dgoosefs.user.file.metadata.sync.interval=0 --replication $replica $path
diff --git a/charts/fluid-dataloader/jindo/templates/configmap.yaml b/charts/fluid-dataloader/jindo/templates/configmap.yaml
--- a/charts/fluid-dataloader/jindo/templates/configmap.yaml
+++ b/charts/fluid-dataloader/jindo/templates/configmap.yaml
@@ -30,6 +30,16 @@ data:
   dataloader.distributedLoad: |
     #!/usr/bin/env bash
     set -xe
+    
+    function checkPathExistence() {
+        local targetPath=$1
+        local checkPathResult=$(timeout 30s hadoop fs -ls jfs://jindo$targetPath &>checkPath.log || tail -3 checkPath.log)
+        local strUnexistence="No such file or directory"
+        if [[ $checkPathResult =~ $strUnexistence ]];then
+            echo -e "dataLoad failed because some paths not exist."
+            exit 1
+        fi
+    }
 
     function distributedLoad() {
         local path=$1
