Github actions support crd validation (#2106)
* Github actions support crd validation

Signed-off-by: dongyun.xzh <dongyun.xzh@alibaba-inc.com>

* Github actions support crd validation

Signed-off-by: dongyun.xzh <dongyun.xzh@alibaba-inc.com>

* Update AlluxioRuntime golang types

Signed-off-by: dongyun.xzh <dongyun.xzh@alibaba-inc.com>

Signed-off-by: dongyun.xzh <dongyun.xzh@alibaba-inc.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -13,6 +13,31 @@ jobs:
       - uses: actions/checkout@v3
       - uses: dominikh/staticcheck-action@v1
 
+  crd-validation:
+    runs-on: ubuntu-latest
+    env:
+      GOPATH: ${{ github.workspace }}
+      GO111MODULE: auto
+    defaults:
+      run:
+        working-directory: ${{ env.GOPATH }}/src/github.com/fluid-cloudnative/fluid
+    steps:
+      - name: Set up Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.17
+
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          path: ${{ env.GOPATH }}/src/github.com/fluid-cloudnative/fluid
+
+      - name: CRD validation check
+        run: |
+          make update-crd
+          git status --porcelain
+          if [ -z "`git status --porcelain`" ]; then echo "CRD validation passed."; else echo "CRD validation failed. Please use 'make update-crd' to keep CRDs latest"; exit 1; fi
+
   build:
     env:
       GOPATH: ${{ github.workspace }}
