Modify github actions workflow
Signed-off-by: dongyun.xzh <dongyun.xzh@alibaba-inc.com>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -13,7 +13,7 @@ jobs:
       - uses: actions/checkout@v3
       - uses: dominikh/staticcheck-action@v1
 
-  crd-validation:
+  lint:
     runs-on: ubuntu-latest
     env:
       GOPATH: ${{ github.workspace }}
@@ -32,11 +32,26 @@ jobs:
         with:
           path: ${{ env.GOPATH }}/src/github.com/fluid-cloudnative/fluid
 
+      - name: Lint preparation
+        run: |
+          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
+          arch=$(go env GOARCH)
+          os=$(go env GOOS)
+          curl -L https://get.helm.sh/helm-v3.7.2-${os}-${arch}.tar.gz | tar -xz -C /tmp
+          chmod u+x /tmp/${os}-${arch}/helm && sudo mv /tmp/${os}-${arch}/helm /usr/local/bin/helm
+
       - name: CRD validation check
         run: |
           make update-crd
           git status --porcelain
           if [ -z "`git status --porcelain`" ]; then echo "CRD validation passed."; else echo "CRD validation failed. Please use 'make update-crd' to keep CRDs latest"; exit 1; fi
+
+      - name: Project vet
+        run: |
+          golangci-lint run --timeout=10m
+          test -z "$(go fmt ./... 2>/dev/null | tee /dev/stderr)" || (echo "please format Go code with 'gofmt'")
+          go vet ./...
+          find ./charts | grep Chart.yaml | xargs dirname | xargs helm lint
 
   build:
     env:
@@ -60,23 +75,16 @@ jobs:
 
     - name: CI Preparation
       run: |
-        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.30.0
         arch=$(go env GOARCH)
         os=$(go env GOOS)
         curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_${os}_${arch}.tar.gz | tar -xz -C /tmp/
         sudo mv /tmp/kubebuilder_2.3.1_${os}_${arch} /usr/local/kubebuilder
         export PATH=$PATH:/usr/local/kubebuilder/bin
-        curl -L https://get.helm.sh/helm-v3.7.2-${os}-${arch}.tar.gz | tar -xz -C /tmp
-        chmod u+x /tmp/${os}-${arch}/helm && sudo mv /tmp/${os}-${arch}/helm /usr/local/bin/helm
-        cp /usr/local/bin/helm /usr/local/bin/ddc-helm
-    
+
     - name: CI script
       run: |
-        golangci-lint run --timeout=10m ./...
-        test -z "$(go fmt ./... 2>/dev/null | tee /dev/stderr)" || (echo "please format Go code with 'gofmt'")
-        go vet ./...
-        make manifests
         make build
-        find ./charts | grep Chart.yaml | xargs dirname | xargs helm lint
         make test
+        git status --porcelain | grep generated
+        if [ -z "$(git status --porcelain | grep generated)" ]; then echo "openapi validation passed."; else echo "openapi validation failed. Please use 'make build' to generate openapi"; exit 1; fi
         bash <(curl -s https://codecov.io/bash)
